import Gas from './gas';
// const Gas = require('./gas');
const gas = new Gas();

gas.getRegisterUserGas(1).then(console.log);


// { levelPercent: [Function: bound _createTxObject],
//     '0x028f3f88': [Function: bound _createTxObject],
//     'levelPercent(uint8)': [Function: bound _createTxObject],
//     creator: [Function: bound _createTxObject],
//     '0x02d05d3f': [Function: bound _createTxObject],
//     'creator()': [Function: bound _createTxObject],
//     buyFruit_UI: [Function: bound _createTxObject],
//     '0x100a4508': [Function: bound _createTxObject],
//     'buyFruit_UI(address,uint8)': [Function: bound _createTxObject],
//     getUserReferrals_UI: [Function: bound _createTxObject],
//     '0x181adcb6': [Function: bound _createTxObject],
//     'getUserReferrals_UI(address)': [Function: bound _createTxObject],
//     withdrawIncome_UI: [Function: bound _createTxObject],
//     '0x29476ef6': [Function: bound _createTxObject],
//     'withdrawIncome_UI(address)': [Function: bound _createTxObject],
//     usersArray: [Function: bound _createTxObject],
//     '0x2fae35c0': [Function: bound _createTxObject],
//     'usersArray(uint256)': [Function: bound _createTxObject],
//     getUserAccount_UI: [Function: bound _createTxObject],
//     '0x3b4c755a': [Function: bound _createTxObject],
//     'getUserAccount_UI(address)': [Function: bound _createTxObject],
//     getUserInfo_UI: [Function: bound _createTxObject],
//     '0x424d8a17': [Function: bound _createTxObject],
//     'getUserInfo_UI(address)': [Function: bound _createTxObject],
//     userAddresses: [Function: bound _createTxObject],
//     '0x502c9bd5': [Function: bound _createTxObject],
//     'userAddresses(uint256)': [Function: bound _createTxObject],
//     accounts: [Function: bound _createTxObject],
//     '0x5e5c06e2': [Function: bound _createTxObject],
//     'accounts(address)': [Function: bound _createTxObject],
//     login_UI: [Function: bound _createTxObject],
//     '0x616100df': [Function: bound _createTxObject],
//     'login_UI(address)': [Function: bound _createTxObject],
//     lotteryMoney: [Function: bound _createTxObject],
//     '0x8431148c': [Function: bound _createTxObject],
//     'lotteryMoney()': [Function: bound _createTxObject],
//     conutReferralsNum_UI: [Function: bound _createTxObject],
//     '0xa6fd8007': [Function: bound _createTxObject],
//     'conutReferralsNum_UI(uint256)': [Function: bound _createTxObject],
//     currentUserID: [Function: bound _createTxObject],
//     '0xa9a5b781': [Function: bound _createTxObject],
//     'currentUserID()': [Function: bound _createTxObject],
//     drawLottery_UI: [Function: bound _createTxObject],
//     '0xaa5fe7c1': [Function: bound _createTxObject],
//     'drawLottery_UI()': [Function: bound _createTxObject],
//     withdrawcCash_UI: [Function: bound _createTxObject],
//     '0xb522261d': [Function: bound _createTxObject],
//     'withdrawcCash_UI(address)': [Function: bound _createTxObject],
//     registerUser_UI: [Function: bound _createTxObject],
//     '0xb8647c1c': [Function: bound _createTxObject],
//     'registerUser_UI(uint16)': [Function: bound _createTxObject],
//     developer: [Function: bound _createTxObject],
//     '0xca4b208b': [Function: bound _createTxObject],
//     'developer()': [Function: bound _createTxObject],
//     effectUsers: [Function: bound _createTxObject],
//     '0xd557086c': [Function: bound _createTxObject],
//     'effectUsers(uint256)': [Function: bound _createTxObject],
//     getAccountPromotions_UI: [Function: bound _createTxObject],
//     '0xee7ac61b': [Function: bound _createTxObject],
//     'getAccountPromotions_UI(address)': [Function: bound _createTxObject] }